api:
  url: "https://api.spacexdata.com/v4/launches"  # Пример API SpaceX

database:
  host: "172.20.0.4"
  port: 5432
  dbname: "postgres"
  user: "airflow"
  password: "airflow"
  table_name: "spacex_launches"